version: '3.7'
volumes:
  postgres_data:
  static_volume:
  es_data:


services:
  db:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_OPTIONS=${POSTGRES_OPTIONS}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  admin_panel:
    container_name: admin_panel
    build: movies_admin/.
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_OPTIONS=${POSTGRES_OPTIONS}
    volumes:
      - ./movies_admin/config/static:/code/static
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./movies_admin/config/static:/code/static

    ports:
      - "80:80"
    depends_on:
      - admin_panel
