version: '3.7'
volumes:
  postgres_data:
  static_volume:


services:
  db:
    container_name: postgres
    image: postgres:13
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  admin_panel:
    container_name: admin_panel
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./movies_admin/config/static:/code/static
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./movies_admin/config/static:/code/static

    ports:
      - "80:80"
    depends_on:
      - admin_panel
