# Generated by Django 3.1 on 2021-08-16 10:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmWork',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('creation_date', models.DateField(default=None, null=True, verbose_name='Date of creation of film')),
                ('certificate', models.TextField(blank=True, null=True, verbose_name='Certificate')),
                ('file_path', models.FileField(default=None, null=True, upload_to='film_work/', verbose_name='File path')),
                ('rating', models.FloatField(default=None, null=True, verbose_name='Rating')),
                ('type', models.CharField(blank=True, choices=[('film', 'film'), ('series', 'series'), ('tv_show', 'tv_show')], max_length=50, verbose_name='Type')),
                ('mpaa_rating', models.CharField(blank=True, choices=[('general', 'G — General audiences'), ('parental_guidance', 'PG — Parental guidance suggested'), ('parental_guidance_strong', 'PG-13 — Parents strongly cautioned'), ('restricted', 'R — Restricted'), ('no_one_17_under', 'NC-17 — No One 17 & Under Admitted')], max_length=50, verbose_name='MPAA film rating')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
                'db_table': 'content.film_work',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.TextField(verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'content.genre',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('full_name', models.TextField(verbose_name='Full name')),
                ('birth_date', models.DateField(default=None, null=True, verbose_name='Birth date')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'content.person',
            },
        ),
        migrations.CreateModel(
            name='FilmWorkPerson',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('role', models.CharField(choices=[('actor', 'actor'), ('writer', 'writer'), ('director', 'director')], max_length=50, verbose_name='Role')),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_v1.filmwork')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_v1.person')),
            ],
            options={
                'verbose_name': 'Connection Film to Person',
                'verbose_name_plural': 'Connections Film to Person',
                'db_table': 'content.film_work_person',
                'unique_together': {('film_work', 'person', 'role')},
            },
        ),
        migrations.CreateModel(
            name='FilmWorkGenre',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_v1.filmwork')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_v1.genre')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'content.film_work_genre',
                'unique_together': {('film_work', 'genre')},
            },
        ),
        migrations.AddField(
            model_name='filmwork',
            name='genres',
            field=models.ManyToManyField(through='movies_v1.FilmWorkGenre', to='movies_v1.Genre'),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='persons',
            field=models.ManyToManyField(through='movies_v1.FilmWorkPerson', to='movies_v1.Person'),
        ),
    ]
