# Generated by Django 3.1 on 2021-08-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='indexed',
            field=models.BooleanField(default=False, verbose_name='elasticsearch in indexed'),
        ),
        migrations.AddField(
            model_name='filmworkgenre',
            name='indexed',
            field=models.BooleanField(default=False, verbose_name='elasticsearch in indexed'),
        ),
        migrations.AddField(
            model_name='filmworkperson',
            name='indexed',
            field=models.BooleanField(default=False, verbose_name='elasticsearch in indexed'),
        ),
        migrations.AddField(
            model_name='genre',
            name='indexed',
            field=models.BooleanField(default=False, verbose_name='elasticsearch in indexed'),
        ),
        migrations.AddField(
            model_name='person',
            name='indexed',
            field=models.BooleanField(default=False, verbose_name='elasticsearch in indexed'),
        ),
    ]
